// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var releases = Releases.FromJson(jsonString);

using System;
using Newtonsoft.Json;

namespace NetExtender.Git
{
    public class GitHubRelease
    {
        [JsonProperty("url")]
        public Uri Url { get; private set; }

        [JsonProperty("assets_url")]
        public Uri AssetsUrl { get; private set; }

        [JsonProperty("upload_url")]
        public String UploadUrl { get; private set; }

        [JsonProperty("html_url")]
        public Uri HtmlUrl { get; private set; }

        [JsonProperty("id")]
        public Int64 Id { get; private set; }

        [JsonProperty("node_id")]
        public String NodeId { get; private set; }

        [JsonProperty("tag_name")]
        public String TagName { get; private set; }

        [JsonProperty("target_commitish")]
        public String TargetCommitish { get; private set; }

        [JsonProperty("name")]
        public String Name { get; private set; }

        [JsonProperty("draft")]
        public Boolean Draft { get; private set; }

        [JsonProperty("author")]
        public Author AuthorName { get; private set; }

        [JsonProperty("prerelease")]
        public Boolean PreRelease { get; private set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; private set; }

        [JsonProperty("published_at")]
        public DateTimeOffset PublishedAt { get; private set; }

        [JsonProperty("assets")]
        public Asset[] Assets { get; private set; }

        [JsonProperty("tarball_url")]
        public Uri TarballUrl { get; private set; }

        [JsonProperty("zipball_url")]
        public Uri ZipballUrl { get; private set; }

        [JsonProperty("body")]
        public String Body { get; private set; }

        [JsonConstructor]
        private GitHubRelease()
        {
        }
    }
    
    public class Asset
    {
        [JsonProperty("url")]
        public Uri Url { get; private set; }

        [JsonProperty("id")]
        public Int64 Id { get; private set; }

        [JsonProperty("node_id")]
        public String NodeId { get; private set; }

        [JsonProperty("name")]
        public String Name { get; private set; }

        [JsonProperty("label")]
        public Object Label { get; private set; }

        [JsonProperty("uploader")]
        public Author Uploader { get; private set; }

        [JsonProperty("content_type")]
        public String ContentType { get; private set; }

        [JsonProperty("state")]
        public String State { get; private set; }

        [JsonProperty("size")]
        public Int64 Size { get; private set; }

        [JsonProperty("download_count")]
        public Int64 DownloadCount { get; private set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; private set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; private set; }

        [JsonProperty("browser_download_url")]
        public Uri BrowserDownloadUrl { get; private set; }
        
        [JsonConstructor]
        private Asset()
        {
        }
    }
    
    public class Author
    {
        [JsonProperty("login")]
        public String Login { get; private set; }

        [JsonProperty("id")]
        public Int64 Id { get; private set; }

        [JsonProperty("node_id")]
        public String NodeId { get; private set; }

        [JsonProperty("avatar_url")]
        public Uri AvatarUrl { get; private set; }

        [JsonProperty("url")]
        public Uri Url { get; private set; }
        
        [JsonConstructor]
        private Author()
        {
        }
    }
}