//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StrongId source generator
//
//     Changes to this file will be lost if code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
#pragma warning disable 1591 // publicly visible type or member must be documented

