using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace NetExtender.Images.Flags
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [DebuggerNonUserCode]
    [CompilerGenerated]
    public class FlagsImages
    {
        private static ResourceManager Manager { get; set; }

        private static CultureInfo Resource { get; set; }

        internal FlagsImages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (!ReferenceEquals(Manager, null))
                {
                    return Manager;
                }

                ResourceManager temp = new ResourceManager("NetExtender.Images.Flags.FlagsImages", typeof(FlagsImages).Assembly);
                Manager = temp;

                return Manager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return Resource;
            }
            set
            {
                Resource = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _as
        {
            get
            {
                Object obj = ResourceManager.GetObject("_as", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _do
        {
            get
            {
                Object obj = ResourceManager.GetObject("_do", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _in
        {
            get
            {
                Object obj = ResourceManager.GetObject("_in", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap _is
        {
            get
            {
                Object obj = ResourceManager.GetObject("_is", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ad
        {
            get
            {
                Object obj = ResourceManager.GetObject("ad", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ae
        {
            get
            {
                Object obj = ResourceManager.GetObject("ae", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap af
        {
            get
            {
                Object obj = ResourceManager.GetObject("af", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ag
        {
            get
            {
                Object obj = ResourceManager.GetObject("ag", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ai
        {
            get
            {
                Object obj = ResourceManager.GetObject("ai", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap al
        {
            get
            {
                Object obj = ResourceManager.GetObject("al", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap am
        {
            get
            {
                Object obj = ResourceManager.GetObject("am", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap an
        {
            get
            {
                Object obj = ResourceManager.GetObject("an", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ao
        {
            get
            {
                Object obj = ResourceManager.GetObject("ao", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ar
        {
            get
            {
                Object obj = ResourceManager.GetObject("ar", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap at
        {
            get
            {
                Object obj = ResourceManager.GetObject("at", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap au
        {
            get
            {
                Object obj = ResourceManager.GetObject("au", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap aw
        {
            get
            {
                Object obj = ResourceManager.GetObject("aw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ax
        {
            get
            {
                Object obj = ResourceManager.GetObject("ax", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap az
        {
            get
            {
                Object obj = ResourceManager.GetObject("az", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ba
        {
            get
            {
                Object obj = ResourceManager.GetObject("ba", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bb
        {
            get
            {
                Object obj = ResourceManager.GetObject("bb", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bd
        {
            get
            {
                Object obj = ResourceManager.GetObject("bd", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap be
        {
            get
            {
                Object obj = ResourceManager.GetObject("be", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bf
        {
            get
            {
                Object obj = ResourceManager.GetObject("bf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bg
        {
            get
            {
                Object obj = ResourceManager.GetObject("bg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bh
        {
            get
            {
                Object obj = ResourceManager.GetObject("bh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bi
        {
            get
            {
                Object obj = ResourceManager.GetObject("bi", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bj
        {
            get
            {
                Object obj = ResourceManager.GetObject("bj", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bm
        {
            get
            {
                Object obj = ResourceManager.GetObject("bm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bn
        {
            get
            {
                Object obj = ResourceManager.GetObject("bn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bo
        {
            get
            {
                Object obj = ResourceManager.GetObject("bo", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap br
        {
            get
            {
                Object obj = ResourceManager.GetObject("br", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bs
        {
            get
            {
                Object obj = ResourceManager.GetObject("bs", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bt
        {
            get
            {
                Object obj = ResourceManager.GetObject("bt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bv
        {
            get
            {
                Object obj = ResourceManager.GetObject("bv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bw
        {
            get
            {
                Object obj = ResourceManager.GetObject("bw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap by
        {
            get
            {
                Object obj = ResourceManager.GetObject("by", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap bz
        {
            get
            {
                Object obj = ResourceManager.GetObject("bz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ca
        {
            get
            {
                Object obj = ResourceManager.GetObject("ca", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap catalonia
        {
            get
            {
                Object obj = ResourceManager.GetObject("catalonia", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cc
        {
            get
            {
                Object obj = ResourceManager.GetObject("cc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cd
        {
            get
            {
                Object obj = ResourceManager.GetObject("cd", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cf
        {
            get
            {
                Object obj = ResourceManager.GetObject("cf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cg
        {
            get
            {
                Object obj = ResourceManager.GetObject("cg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ch
        {
            get
            {
                Object obj = ResourceManager.GetObject("ch", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ci
        {
            get
            {
                Object obj = ResourceManager.GetObject("ci", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ck
        {
            get
            {
                Object obj = ResourceManager.GetObject("ck", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cl
        {
            get
            {
                Object obj = ResourceManager.GetObject("cl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cm
        {
            get
            {
                Object obj = ResourceManager.GetObject("cm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cn
        {
            get
            {
                Object obj = ResourceManager.GetObject("cn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap co
        {
            get
            {
                Object obj = ResourceManager.GetObject("co", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cr
        {
            get
            {
                Object obj = ResourceManager.GetObject("cr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cs
        {
            get
            {
                Object obj = ResourceManager.GetObject("cs", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cu
        {
            get
            {
                Object obj = ResourceManager.GetObject("cu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cv
        {
            get
            {
                Object obj = ResourceManager.GetObject("cv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cw
        {
            get
            {
                Object obj = ResourceManager.GetObject("cw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cx
        {
            get
            {
                Object obj = ResourceManager.GetObject("cx", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cy
        {
            get
            {
                Object obj = ResourceManager.GetObject("cy", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap cz
        {
            get
            {
                Object obj = ResourceManager.GetObject("cz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap dd
        {
            get
            {
                Object obj = ResourceManager.GetObject("dd", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap de
        {
            get
            {
                Object obj = ResourceManager.GetObject("de", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap dj
        {
            get
            {
                Object obj = ResourceManager.GetObject("dj", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap dk
        {
            get
            {
                Object obj = ResourceManager.GetObject("dk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap dm
        {
            get
            {
                Object obj = ResourceManager.GetObject("dm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap dz
        {
            get
            {
                Object obj = ResourceManager.GetObject("dz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ec
        {
            get
            {
                Object obj = ResourceManager.GetObject("ec", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ee
        {
            get
            {
                Object obj = ResourceManager.GetObject("ee", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap eg
        {
            get
            {
                Object obj = ResourceManager.GetObject("eg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap eh
        {
            get
            {
                Object obj = ResourceManager.GetObject("eh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap en
        {
            get
            {
                Object obj = ResourceManager.GetObject("en", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap er
        {
            get
            {
                Object obj = ResourceManager.GetObject("er", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap es
        {
            get
            {
                Object obj = ResourceManager.GetObject("es", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap et
        {
            get
            {
                Object obj = ResourceManager.GetObject("et", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap eu
        {
            get
            {
                Object obj = ResourceManager.GetObject("eu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fi
        {
            get
            {
                Object obj = ResourceManager.GetObject("fi", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fj
        {
            get
            {
                Object obj = ResourceManager.GetObject("fj", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fk
        {
            get
            {
                Object obj = ResourceManager.GetObject("fk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fm
        {
            get
            {
                Object obj = ResourceManager.GetObject("fm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fo
        {
            get
            {
                Object obj = ResourceManager.GetObject("fo", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fr
        {
            get
            {
                Object obj = ResourceManager.GetObject("fr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ga
        {
            get
            {
                Object obj = ResourceManager.GetObject("ga", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gb
        {
            get
            {
                Object obj = ResourceManager.GetObject("gb", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gd
        {
            get
            {
                Object obj = ResourceManager.GetObject("gd", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ge
        {
            get
            {
                Object obj = ResourceManager.GetObject("ge", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gf
        {
            get
            {
                Object obj = ResourceManager.GetObject("gf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gg
        {
            get
            {
                Object obj = ResourceManager.GetObject("gg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gh
        {
            get
            {
                Object obj = ResourceManager.GetObject("gh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gi
        {
            get
            {
                Object obj = ResourceManager.GetObject("gi", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gl
        {
            get
            {
                Object obj = ResourceManager.GetObject("gl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gm
        {
            get
            {
                Object obj = ResourceManager.GetObject("gm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gn
        {
            get
            {
                Object obj = ResourceManager.GetObject("gn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gp
        {
            get
            {
                Object obj = ResourceManager.GetObject("gp", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gq
        {
            get
            {
                Object obj = ResourceManager.GetObject("gq", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gr
        {
            get
            {
                Object obj = ResourceManager.GetObject("gr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gs
        {
            get
            {
                Object obj = ResourceManager.GetObject("gs", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gt
        {
            get
            {
                Object obj = ResourceManager.GetObject("gt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gu
        {
            get
            {
                Object obj = ResourceManager.GetObject("gu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gw
        {
            get
            {
                Object obj = ResourceManager.GetObject("gw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap gy
        {
            get
            {
                Object obj = ResourceManager.GetObject("gy", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap hk
        {
            get
            {
                Object obj = ResourceManager.GetObject("hk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap hm
        {
            get
            {
                Object obj = ResourceManager.GetObject("hm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap hn
        {
            get
            {
                Object obj = ResourceManager.GetObject("hn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap hr
        {
            get
            {
                Object obj = ResourceManager.GetObject("hr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ht
        {
            get
            {
                Object obj = ResourceManager.GetObject("ht", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap hu
        {
            get
            {
                Object obj = ResourceManager.GetObject("hu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap id
        {
            get
            {
                Object obj = ResourceManager.GetObject("id", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ie
        {
            get
            {
                Object obj = ResourceManager.GetObject("ie", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap il
        {
            get
            {
                Object obj = ResourceManager.GetObject("il", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap io
        {
            get
            {
                Object obj = ResourceManager.GetObject("io", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap iq
        {
            get
            {
                Object obj = ResourceManager.GetObject("iq", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ir
        {
            get
            {
                Object obj = ResourceManager.GetObject("ir", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap it
        {
            get
            {
                Object obj = ResourceManager.GetObject("it", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap jm
        {
            get
            {
                Object obj = ResourceManager.GetObject("jm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap jo
        {
            get
            {
                Object obj = ResourceManager.GetObject("jo", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap jp
        {
            get
            {
                Object obj = ResourceManager.GetObject("jp", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ke
        {
            get
            {
                Object obj = ResourceManager.GetObject("ke", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kg
        {
            get
            {
                Object obj = ResourceManager.GetObject("kg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kh
        {
            get
            {
                Object obj = ResourceManager.GetObject("kh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ki
        {
            get
            {
                Object obj = ResourceManager.GetObject("ki", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap km
        {
            get
            {
                Object obj = ResourceManager.GetObject("km", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kn
        {
            get
            {
                Object obj = ResourceManager.GetObject("kn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kp
        {
            get
            {
                Object obj = ResourceManager.GetObject("kp", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kr
        {
            get
            {
                Object obj = ResourceManager.GetObject("kr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kw
        {
            get
            {
                Object obj = ResourceManager.GetObject("kw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ky
        {
            get
            {
                Object obj = ResourceManager.GetObject("ky", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap kz
        {
            get
            {
                Object obj = ResourceManager.GetObject("kz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap la
        {
            get
            {
                Object obj = ResourceManager.GetObject("la", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lb
        {
            get
            {
                Object obj = ResourceManager.GetObject("lb", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lc
        {
            get
            {
                Object obj = ResourceManager.GetObject("lc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap li
        {
            get
            {
                Object obj = ResourceManager.GetObject("li", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lk
        {
            get
            {
                Object obj = ResourceManager.GetObject("lk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lr
        {
            get
            {
                Object obj = ResourceManager.GetObject("lr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ls
        {
            get
            {
                Object obj = ResourceManager.GetObject("ls", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lt
        {
            get
            {
                Object obj = ResourceManager.GetObject("lt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lu
        {
            get
            {
                Object obj = ResourceManager.GetObject("lu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap lv
        {
            get
            {
                Object obj = ResourceManager.GetObject("lv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ly
        {
            get
            {
                Object obj = ResourceManager.GetObject("ly", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ma
        {
            get
            {
                Object obj = ResourceManager.GetObject("ma", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mc
        {
            get
            {
                Object obj = ResourceManager.GetObject("mc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap md
        {
            get
            {
                Object obj = ResourceManager.GetObject("md", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap me
        {
            get
            {
                Object obj = ResourceManager.GetObject("me", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mg
        {
            get
            {
                Object obj = ResourceManager.GetObject("mg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mh
        {
            get
            {
                Object obj = ResourceManager.GetObject("mh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mk
        {
            get
            {
                Object obj = ResourceManager.GetObject("mk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ml
        {
            get
            {
                Object obj = ResourceManager.GetObject("ml", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mm
        {
            get
            {
                Object obj = ResourceManager.GetObject("mm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mn
        {
            get
            {
                Object obj = ResourceManager.GetObject("mn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mo
        {
            get
            {
                Object obj = ResourceManager.GetObject("mo", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mp
        {
            get
            {
                Object obj = ResourceManager.GetObject("mp", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mq
        {
            get
            {
                Object obj = ResourceManager.GetObject("mq", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mr
        {
            get
            {
                Object obj = ResourceManager.GetObject("mr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ms
        {
            get
            {
                Object obj = ResourceManager.GetObject("ms", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mt
        {
            get
            {
                Object obj = ResourceManager.GetObject("mt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mu
        {
            get
            {
                Object obj = ResourceManager.GetObject("mu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mv
        {
            get
            {
                Object obj = ResourceManager.GetObject("mv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mw
        {
            get
            {
                Object obj = ResourceManager.GetObject("mw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mx
        {
            get
            {
                Object obj = ResourceManager.GetObject("mx", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap my
        {
            get
            {
                Object obj = ResourceManager.GetObject("my", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap mz
        {
            get
            {
                Object obj = ResourceManager.GetObject("mz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap na
        {
            get
            {
                Object obj = ResourceManager.GetObject("na", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nc
        {
            get
            {
                Object obj = ResourceManager.GetObject("nc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ne
        {
            get
            {
                Object obj = ResourceManager.GetObject("ne", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nf
        {
            get
            {
                Object obj = ResourceManager.GetObject("nf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ng
        {
            get
            {
                Object obj = ResourceManager.GetObject("ng", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ni
        {
            get
            {
                Object obj = ResourceManager.GetObject("ni", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nl
        {
            get
            {
                Object obj = ResourceManager.GetObject("nl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap no
        {
            get
            {
                Object obj = ResourceManager.GetObject("no", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap np
        {
            get
            {
                Object obj = ResourceManager.GetObject("np", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nr
        {
            get
            {
                Object obj = ResourceManager.GetObject("nr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nu
        {
            get
            {
                Object obj = ResourceManager.GetObject("nu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap nz
        {
            get
            {
                Object obj = ResourceManager.GetObject("nz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap om
        {
            get
            {
                Object obj = ResourceManager.GetObject("om", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pa
        {
            get
            {
                Object obj = ResourceManager.GetObject("pa", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pe
        {
            get
            {
                Object obj = ResourceManager.GetObject("pe", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pf
        {
            get
            {
                Object obj = ResourceManager.GetObject("pf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pg
        {
            get
            {
                Object obj = ResourceManager.GetObject("pg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ph
        {
            get
            {
                Object obj = ResourceManager.GetObject("ph", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pk
        {
            get
            {
                Object obj = ResourceManager.GetObject("pk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pl
        {
            get
            {
                Object obj = ResourceManager.GetObject("pl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pm
        {
            get
            {
                Object obj = ResourceManager.GetObject("pm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pn
        {
            get
            {
                Object obj = ResourceManager.GetObject("pn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pr
        {
            get
            {
                Object obj = ResourceManager.GetObject("pr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ps
        {
            get
            {
                Object obj = ResourceManager.GetObject("ps", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pt
        {
            get
            {
                Object obj = ResourceManager.GetObject("pt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap pw
        {
            get
            {
                Object obj = ResourceManager.GetObject("pw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap py
        {
            get
            {
                Object obj = ResourceManager.GetObject("py", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap qa
        {
            get
            {
                Object obj = ResourceManager.GetObject("qa", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap re
        {
            get
            {
                Object obj = ResourceManager.GetObject("re", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ro
        {
            get
            {
                Object obj = ResourceManager.GetObject("ro", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rs
        {
            get
            {
                Object obj = ResourceManager.GetObject("rs", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ru
        {
            get
            {
                Object obj = ResourceManager.GetObject("ru", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rw
        {
            get
            {
                Object obj = ResourceManager.GetObject("rw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sa
        {
            get
            {
                Object obj = ResourceManager.GetObject("sa", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sb
        {
            get
            {
                Object obj = ResourceManager.GetObject("sb", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sc
        {
            get
            {
                Object obj = ResourceManager.GetObject("sc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap scotland
        {
            get
            {
                Object obj = ResourceManager.GetObject("scotland", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sd
        {
            get
            {
                Object obj = ResourceManager.GetObject("sd", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap se
        {
            get
            {
                Object obj = ResourceManager.GetObject("se", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sg
        {
            get
            {
                Object obj = ResourceManager.GetObject("sg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sh
        {
            get
            {
                Object obj = ResourceManager.GetObject("sh", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap si
        {
            get
            {
                Object obj = ResourceManager.GetObject("si", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sj
        {
            get
            {
                Object obj = ResourceManager.GetObject("sj", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sk
        {
            get
            {
                Object obj = ResourceManager.GetObject("sk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sl
        {
            get
            {
                Object obj = ResourceManager.GetObject("sl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sm
        {
            get
            {
                Object obj = ResourceManager.GetObject("sm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sn
        {
            get
            {
                Object obj = ResourceManager.GetObject("sn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap so
        {
            get
            {
                Object obj = ResourceManager.GetObject("so", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sr
        {
            get
            {
                Object obj = ResourceManager.GetObject("sr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap st
        {
            get
            {
                Object obj = ResourceManager.GetObject("st", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sv
        {
            get
            {
                Object obj = ResourceManager.GetObject("sv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sy
        {
            get
            {
                Object obj = ResourceManager.GetObject("sy", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap sz
        {
            get
            {
                Object obj = ResourceManager.GetObject("sz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tc
        {
            get
            {
                Object obj = ResourceManager.GetObject("tc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap td
        {
            get
            {
                Object obj = ResourceManager.GetObject("td", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tf
        {
            get
            {
                Object obj = ResourceManager.GetObject("tf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tg
        {
            get
            {
                Object obj = ResourceManager.GetObject("tg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap th
        {
            get
            {
                Object obj = ResourceManager.GetObject("th", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tj
        {
            get
            {
                Object obj = ResourceManager.GetObject("tj", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tk
        {
            get
            {
                Object obj = ResourceManager.GetObject("tk", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tl
        {
            get
            {
                Object obj = ResourceManager.GetObject("tl", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tm
        {
            get
            {
                Object obj = ResourceManager.GetObject("tm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tn
        {
            get
            {
                Object obj = ResourceManager.GetObject("tn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap to
        {
            get
            {
                Object obj = ResourceManager.GetObject("to", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tr
        {
            get
            {
                Object obj = ResourceManager.GetObject("tr", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tt
        {
            get
            {
                Object obj = ResourceManager.GetObject("tt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tv
        {
            get
            {
                Object obj = ResourceManager.GetObject("tv", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tw
        {
            get
            {
                Object obj = ResourceManager.GetObject("tw", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap tz
        {
            get
            {
                Object obj = ResourceManager.GetObject("tz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ua
        {
            get
            {
                Object obj = ResourceManager.GetObject("ua", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ug
        {
            get
            {
                Object obj = ResourceManager.GetObject("ug", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap um
        {
            get
            {
                Object obj = ResourceManager.GetObject("um", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap us
        {
            get
            {
                Object obj = ResourceManager.GetObject("us", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap uy
        {
            get
            {
                Object obj = ResourceManager.GetObject("uy", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap uz
        {
            get
            {
                Object obj = ResourceManager.GetObject("uz", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap va
        {
            get
            {
                Object obj = ResourceManager.GetObject("va", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap vc
        {
            get
            {
                Object obj = ResourceManager.GetObject("vc", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ve
        {
            get
            {
                Object obj = ResourceManager.GetObject("ve", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap vg
        {
            get
            {
                Object obj = ResourceManager.GetObject("vg", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap vi
        {
            get
            {
                Object obj = ResourceManager.GetObject("vi", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap vn
        {
            get
            {
                Object obj = ResourceManager.GetObject("vn", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap vu
        {
            get
            {
                Object obj = ResourceManager.GetObject("vu", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap wales
        {
            get
            {
                Object obj = ResourceManager.GetObject("wales", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap wf
        {
            get
            {
                Object obj = ResourceManager.GetObject("wf", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ws
        {
            get
            {
                Object obj = ResourceManager.GetObject("ws", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ye
        {
            get
            {
                Object obj = ResourceManager.GetObject("ye", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap yt
        {
            get
            {
                Object obj = ResourceManager.GetObject("yt", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap za
        {
            get
            {
                Object obj = ResourceManager.GetObject("za", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap zm
        {
            get
            {
                Object obj = ResourceManager.GetObject("zm", Resource);
                return (Bitmap) obj;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap zw
        {
            get
            {
                Object obj = ResourceManager.GetObject("zw", Resource);
                return (Bitmap) obj;
            }
        }
    }
}